import React, { useState } from "react";
import Canvas from "./Canvas";

function App() {
    const [generatedImage, setGeneratedImage] = useState(null); // State to hold the returned image

    return (
        <div style={styles.appContainer}>
            <h1 style={styles.heading}>Stable Diffusion Image Generation</h1>
            <div style={styles.contentContainer}>
                {/* Left Section: Canvas and Prompt */}
                <div style={styles.leftSection}>
                    <Canvas setGeneratedImage={setGeneratedImage} />
                </div>

                {/* Right Section: Display Returned Image */}
                <div style={styles.rightSection}>
                    {generatedImage ? (
                        <div>
                            <h2>Generated Image:</h2>
                            <img src={generatedImage} alt="Generated by Stable Diffusion" style={styles.generatedImage} />
                        </div>
                    ) : (
                        <div>
                            <h2>Generated Image Will Appear Here</h2>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}

const styles = {
    appContainer: {
        padding: "20px",
    },
    heading: {
        textAlign: "center",
        marginBottom: "20px",
    },
    contentContainer: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
    },
    leftSection: {
        flex: 1,
        marginRight: "20px",
    },
    rightSection: {
        flex: 1,
        borderLeft: "2px solid #ccc",
        paddingLeft: "20px",
    },
    generatedImage: {
        width: "100%",
        maxWidth: "500px",
        height: "auto",
        border: "1px solid #000",
    },
};

export default App;
